import { useCallback } from "react";
import { useSSE } from "../hooks/useSSE.js";
import { useNotifications } from "../context/NotificationContext.jsx";
import NavBar from "./NavBar.jsx";

export default function AppShell({ children }) {
  const { dispatch } = useNotifications();

  // useSSE is already wired — the SSE stream delivers notifications to the reducer.
  // This was completed in LU 4.7. Do not edit this file.
  const handleMessage = useCallback(
    (data) => dispatch({ type: "ADD_NOTIFICATION", payload: data }),
    [dispatch]
  );

  useSSE("/api/notifications/stream", handleMessage);

  return (
    <div>
      <NavBar />
      <main style={{ maxWidth: "720px", margin: "0 auto", padding: "1.5rem" }}>
        {children}
      </main>
    </div>
  );
}
